[package]
name = "desuilabs"
version = "0.0.1"
published-at = "0xb1e187030f3b521fe5c22452ec1308d6b1376d14c407e47d9aa8a63d451699d6"

[dependencies.Launchpad]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/launchpad"
rev = "v1.2.1-testnet"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/nft_protocol"
rev = "v1.2.1-testnet"

[dependencies.LiquidityLayerV1]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/liquidity_layer_v1"
rev = "v1.2.1-testnet"

[addresses]
desuilabs = "0xb1e187030f3b521fe5c22452ec1308d6b1376d14c407e47d9aa8a63d451699d6"
